name: Build & Flash Zephyr Firmware to ESP32

on:
  push:
    branches: [main]

jobs:
  build-and-flash:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Zephyr environment
      run: |
        source zephyrproject/zephyr/zephyr-env.sh
        west update
        west zephyr-export

    - name: Build Zephyr app for ESP32
      run: |
        west build -b esp32  /home/hadoop/zephyr/zephyr/zephyrproject --pristine

    - name: Flash ESP32
      run: |
        west flash
