name: Manually Flash via West

on:
  workflow_dispatch:

jobs:
  flash:
    name: Flash Zephyr ELF to ESP32
    runs-on: [self-hosted, r2]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Download Firmware Artifact
      uses: actions/download-artifact@v4
      with:
        name: firmware
        path: build/zephyr

    - name: Flash with west
      run: |
        # Set the serial port manually (Zephyr doesn't auto-detect)
        export WEST_FLASH_SERIAL_PORT=/dev/ttyUSB1

        # Run west flash using the downloaded build
        west flash -d build
