name: Flash Zephyr Firmware

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  flash:
    runs-on: [self-hosted, r2]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download zephyr build artifact
      uses: actions/download-artifact@v4
      with:
        name: zephyr-firmware
        path: build

    - name: Flash ESP32 with west flash
      run: |
        export WEST_FLASH_SERIAL_PORT=/dev/ttyUSB1
        west flash -d build
