name: Flash Zephyr Firmware

on:
  workflow_dispatch:  # Manual trigger from UI

jobs:
  flash:
    runs-on: [self-hosted]

    steps:
    - name: Checkout (not mandatory, but good practice)
      uses: actions/checkout@v4

    - name: Download Firmware Artifact ZIP
      uses: actions/download-artifact@v4
      with:
        name: zephyr-firmware
        path: artifact-zip

    - name: Unpack ZIP to Folder
      run: |
        mkdir -p unpacked
        unzip artifact-zip/zephyr-firmware.zip -d unpacked
        echo "📂 Listing unpacked files:"
        ls -R unpacked

    - name: Flash to ESP32
      run: |
        ELF_FILE="unpacked/zephyr/zephyr.elf"

        if [ -f "$ELF_FILE" ]; then
          echo "✅ Found $ELF_FILE"
          cd unpacked
          west flash -r esp32 --skip-rebuild
        else
          echo "❌ zephyr.elf not found at expected path: $ELF_FILE"
          exit 1
        fi
