name: Flash Zephyr Firmware

on:
  workflow_dispatch:  # Manual trigger from UI

jobs:
  flash:
    name: 🚀 Flash to ESP32

    runs-on: [self-hosted]
    
    defaults:
      run:
        working-directory: ${{ github.workspace }} 

    steps:
      - name: ⬇️ Download Firmware Artifact
        uses: actions/download-artifact@v4
        with:
          name: zephyr-firmware
          path: firmware

      - name: 🔍 Show Downloaded Firmware
        run: |
          ls -R firmware/
      - name: Source Zephyr Env
        run: |
          source /home/hadoop/zephyr/zephyr/zephyr-env.sh
          echo "ZEPHYR_BASE = $ZEPHYR_BASE"
      # - name: 🛠️ Reconfigure Build Metadata
      #   run: |
      #     cd ${{ github.workspace }}
      #     source /home/hadoop/zephyr/zephyr/zephyr-env.sh
      #     BOARD=$(grep -E '^set\s*\(\s*BOARD\s+[^\s)]+\s*\)' CMakeLists.txt | sed -E 's/^set\s*\(\s*BOARD\s+([^\s)]+)\s*\).*/\1/')
      #     echo "Detected BOARD: $BOARD"
      #     west build -d build  --cmake-only .

      - name: 🚀 Flash to ESP32
        run: |
          cd ${{ github.workspace }}
          sudo apt install esptool.py
          source /home/hadoop/zephyr/zephyr/zephyr-env.sh
          if [ ! -f build/zephyr/zephyr.elf ]; then
            echo "❌ zephyr.elf not found!" && exit 1
          fi
          PORT=$(ls /dev/ttyUSB* | head -n 1)
          echo "📡 Using serial port: $PORT"
          west flash -d build --skip-rebuild -r esp32
