name: Flash Zephyr Firmware

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  flash:
    runs-on: [self-hosted]

    steps:
    - name: Download Firmware Artifact
      uses: actions/download-artifact@v4
      with:
        name: zephyr-firmware
        path: build
        merge-multiple : true

    - name: Unpack Firmware
      run: |
        mkdir -p unpacked
        ls -R unpacked

    - name: Flash to ESP32
      run: |
        cd unpacked/build

        if [ -f zephyr/zephyr.elf ]; then
          echo "Flashing zephyr.elf via west..."
          west flash -r esp32 --skip-rebuild
        else
          echo "zephyr.elf not found!" && exit 1
        fi



        

