name: Manually Flash via West

on:
  workflow_dispatch:

jobs:
  flash:
    name: Flash Zephyr ELF to ESP32
    runs-on: [self-hosted, r2]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Download Firmware Artifact
      uses: actions/download-artifact@v4
      with:
        name: firmware
        path: build

    - name: Flash with west
      run: |
        west flash
