name: Flash Zephyr Firmware

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  flash:
    needs: build
    runs-on: [self-hosted]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download zephyr build artifact
      uses: actions/download-artifact@v4
      with:
        name: zephyr-firmware
        
    - name: Unpack and list files
      run: |
        mkdir -p unpacked
        unzip zephyr-firmware.zip -d unpacked
        ls -R unpacked


    - name: Flash ESP32 with west flash
      run: |
        cd unpacked/build
        export WEST_FLASH_SERIAL_PORT=/dev/ttyUSB1
        west flash -d build


        

